/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QuizQuestion: typeof import('./src/components/QuizQuestion.vue')['default']
    QuizResult: typeof import('./src/components/QuizResult.vue')['default']
    QuizSettings: typeof import('./src/components/QuizSettings.vue')['default']
    QuizTable: typeof import('./src/components/QuizTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./src/components/Rule.vue')['default']
  }
}
